version: "3"
services:
  dns:
    image: joshuasing/lancache-dns:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "${DNS_BIND_IP}:53:53/udp"
      - "${DNS_BIND_IP}:53:53/tcp"

  ## HTTPS requests are now handled in monolithic directly
  ## you could choose to return to sniproxy if desired
  #
  #  sniproxy:
  #    image: joshuasing/sniproxy:latest
  #    env_file: .env
  #    restart: unless-stopped
  #    ports:
  #      - 443:443/tcp

  monolithic:
    image: joshuasing/monolithic:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
